version: '2.1'

services:
  mongo:
    build: ./mongo
    container_name: mongo
    image: feliun/chatbot:mongo
    volumes:
      - ./database:/data # volume in host -> $(pwd)/database
    environment:
      - MONGO_DB_APP_PASSWORD=node
      - MONGO_DB_APP_USERNAME=node
      - MONGO_DB_APP_DATABASE=bots
    ports:
      - '27017:27017'
    healthcheck:
      test: ['CMD', 'echo', 'show dbs', '|', 'mongo']
      interval: 30s
      timeout: 10s
      retries: 3
    command: mongod --smallfiles

networks:
  default:
    external:
      name: local