module.exports = {
  server: {
    host: '0.0.0.0',
    port: 3000,
  },
  mongo: { url: `mongodb://${process.env.MONGO_USER || 'node'}:${process.env.MONGO_PWD || 'node'}@${process.env.MONGO_HOST || '127.0.0.1'}/${process.env.MONGO_DB || 'bots'}` },
  routes: { proxy: { routes: { '/api/1.0/other': 'http://other.example.com' } } },
  logger: {
    transport: 'bunyan',
    include: [
      'tracer',
      'timestamp',
      'level',
      'message',
      'error.message',
      'error.code',
      'error.stack',
      'request.url',
      'request.headers',
      'request.params',
      'request.method',
      'response.statusCode',
      'response.headers',
      'response.time',
      'process',
      'system',
      'package.name',
      'service',
    ],
    exclude: [
      'password',
      'secret',
      'token',
      'request.headers.cookie',
      'dependencies',
      'devDependencies',
    ],
  },
};
